spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestor_documental
    username: postgres
    password: 0043962
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: gestdoc_ow
        format_sql: true
        hbm2ddl:
          auto: validate

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: TRACE
    org.postgresql: DEBUG
