spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestor_documental
    username: postgres
    password: hola2127
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: false 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: gestdoc_ow
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Configuración de almacenamiento de archivos
app:
  upload:
    dir: uploads
  max-file-size-base64: 1048576  # 1MB - archivos menores se guardan como Base64